### ISSUE TITLE
Please make releases available

### ISSUE THREAD

**Issue by deathowl** [ncabatoff/process-exporter#1]
This stuff is great, please make builds available for Linux (X86, X64, ARM builds would be amazing)

**Comment by ncabatoff** [comment]
Sure, I've been meaning to get familiar with Travis CI anyway.  Might not get to it until next week though.

**Comment by roidelapluie** [comment]
:+1:

**Comment by ncabatoff** [comment]
I've got a pre-release up now, let me know if it works for you.  I haven't tested any of builds except linux-amd64.  Note that auto-discovery of CPU/IO-consuming processes has been removed, so if that's a feature you cared about this won't help you.  On the plus side it can now include child process resource consumption, and the numbers are now more accurate.

**Comment by arthur-c** [comment]
Hi @ncabatoff and thanks for the work. This exporter is very helpful!
The latest code allow configuration from a yaml file (-config.path) but it is not released yet, it would be great to have it.

**Comment by ncabatoff** [comment]
Done.
