### ISSUE TITLE
possible incorrect RSS calculation

### ISSUE THREAD

**Issue by raokrutarth** [ncabatoff/process-exporter#105]
I am seeing process_exporter show 200MB+ of memory usage for resident memory:
![image](https://user-images.githubusercontent.com/8570223/59808395-eecfb580-92b0-11e9-8e28-731050cc565c.png)

But top and my custom script on the device keep showing < 50 MB

![image](https://user-images.githubusercontent.com/8570223/59808421-06a73980-92b1-11e9-8f9f-dd84ea45331c.png)

The process in question is `hpe-config`. Is there any reason the RSS in the `top` command would not match the resident memory of `namedprocess_namegroup_memory_bytes`?

**Comment by roman-karpovich** [comment]
Same for me. It's impossible to understand correctly how much memory process used in real.

**Comment by flixr** [comment]
Could it be that this group matches multiple processes/threads and the memory of those is (probably wrongly) being added up?

**Comment by raokrutarth** [comment]
not able to reproduce the issue. closing.

**Comment by dontmint** [comment]
The same thing happened to me. When a process has too many child processes, it starts counting them up, leading to a massive memory usage being displayed
