### ISSUE TITLE
cannot generate metrics while /proc/pid/limits permission denied

### ISSUE THREAD

**Issue by lupenggit** [ncabatoff/process-exporter#106]
I have a process runned by root,and use ordinary user run process_exporter. Now find process_exporter doesnt monit the process .The log tells /proc/pid/limits permission denied . Actually I dont need metrics about limits , just need metrics about load . Is there any way to work aroud it ?

**Comment by ncabatoff** [comment]
Hi @lupenggit,

In very old Linux kernels the /proc/pid/limits file was only readable by the process owner and root.  Since Linux 2.6.36, this file is readable by all users on the system.

I'm probably not going to change process-exporter to accommodate non-root use on such old systems.
