### ISSUE TITLE
How can I ignore children process

### ISSUE THREAD

**Issue by johnnyflute** [ncabatoff/process-exporter#108]
I just want to monitor the parent process, however the metric "namedprocess_namegroup_num_procs" the process exporter expose seems to include the children process

**Comment by sakishrist** [comment]
Can we open this again? I don't seem to be able to find a solution to this.
I have tried `-children false`, `"-children false"` and `-no-children` but none of these seem to work.

I also couldn't find a way to disable this flag by looking into the code.

**Comment by sakishrist** [comment]
OK, found my answer and made a pull request to update the doc with a line describing this:

> To disable any of these options, use the `-option=false`.
