### ISSUE TITLE
Not able to install on Centos6

### ISSUE THREAD

**Issue by gauravrishi168** [ncabatoff/process-exporter#117]
Linux Version:
Linux DR 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I am not able to install the RPM and getting error.

 rpm -ivh process-exporter_0.5.0_linux_386.rpm
Preparing...                ########################################### [100%]
   1:process-exporter       ########################################### [100%]
/var/tmp/rpm-tmp.5jC1hF: line 1: systemctl: command not found
/var/tmp/rpm-tmp.5jC1hF: line 2: systemctl: command not found

**Comment by erude1** [comment]
If you want to install this on EL6 you'll need to create your own init script and manually copy the binary into place. I basically copied what the init script from a process_exporter rpm and that has been working great. I think the following link is the template the one I copied is based on.

https://github.com/lest/prometheus-rpm/blob/master/templates/init.tpl

I think EOL is coming anyway for EL6. Maybe "no EL6 installer" should just be made clearer somewhere (unless it's already clear and I just missed it)?
