### ISSUE TITLE
Build for a Pi?

### ISSUE THREAD

**Issue by bb512** [ncabatoff/process-exporter#118]
Looking to install this build on a Pi 4, but don't see a download.

**Comment by ncabatoff** [comment]
I use the arm64 build on my Pi 3 boxes, as far as I know it should work fine on the Pi 4 too.

**Comment by ncabatoff** [comment]
Correction: turns out I use the armv6 build.  Not sure why because I think the arm64 build ought to work; maybe it's an oversight on my part.  Anyway, at least one and probably both would work on the Pi 4 from what I gather.

**Comment by Rathna-K** [comment]
Hi there! looking for the same for a Pi 4 and docker tags shows only am64, any chance to push the arm versions? TIA!

**Comment by ncabatoff** [comment]
Closing this issue as the original question was answered.  @Rathna-K , @ngosang  - see #194 for the docker-multiarch issue.
