### ISSUE TITLE
[ARM] no metrics extracted

### ISSUE THREAD

**Issue by flixr** [ncabatoff/process-exporter#12]
I'm having a weird problem on my Nvidia Jetson TK1 board (ARMv7) with kernel 3.10.40.

The process-exporter runs without any errors, but there are no named processes collected.

I tried with a "catch-all" yml file
```
process_names:
  - cmdline: 
    - .+
```
as well as simply `./process-exporter -procnames bash -once-to-stdout`

There are no errors in the build/test:
```
>> formatting code
>> vetting code
>> fetching promu
>> building binaries
 >   process-exporter
>> running short tests
?   	github.com/ncabatoff/process-exporter	[no test files]
?   	github.com/ncabatoff/process-exporter/cmd/process-exporter	[no test files]
ok  	github.com/ncabatoff/process-exporter/config	0.011s
ok  	github.com/ncabatoff/process-exporter/proc	0.115s
```

Scrape errors is zero, see the [metrics](https://github.com/ncabatoff/process-exporter/files/1104716/metrics.txt) output

**Comment by ncabatoff** [comment]
Well, I'm at a loss.  I guess this weekend I'll install linux on my chromebit or try to setup a virtual ARM env and see if I can reproduce there.

**Comment by flixr** [comment]
The funny thing is that it runs fine on my Odroid XU4... and in a ARM docker image (using qemu) it just segfaults.

If you have some ideas on how to best debug this further (e.g. even putting some more debug log outputs in the code), I would appreciate it a lot.

**Comment by ncabatoff** [comment]
Oh, interesting.  Well, in terms of debug logs I'd probably start by adding something to Grouper.Update(), e.g. in the iteration over newProcs:

```
         for _, idinfo := range newProcs {
                  wanted, gname := g.namer.MatchAndName(common.NameAndCmdline{idinfo.Name, idinfo.Cmdline})
+                 log.Printf("wanted=%v, gname=%v, idinfo=%v", wanted, gname, idinfo)
```

**Comment by flixr** [comment]
I added that and get no output on the Tegra TK1 (kernel 3.10.40), but as expected it works on the Odroid (kernel 4.2.0)

**Comment by flixr** [comment]
So it seems that because the `/proc/<pid>/io` file does not exist, everything is silently dropped... see TODO in Tracker.Update

**Comment by flixr** [comment]
So I was missing some needed kernel options:
```
CONFIG_TASKSTATS=y
CONFIG_TASK_XACCT=y
CONFIG_TASK_IO_ACCOUNTING=y
```
Then it works...

But it would still be good if the error was caught and logged and even better if the other metrics were still extracted (as per the TODO).

**Comment by ncabatoff** [comment]
Indeed.  Happy to have an explanation.  I'll use this issue to fix the error checking and address the TODO.  Thanks very much for the bug report and analysis.

**Comment by epa095** [comment]
Hi, thanks for a nice tool. Is there any progress on the "io"-TODO? I have problems getting any data from some servers I am running it on, and I think the reason probably is that I dont have read-access to the io folder. To me it seams reasonable that an extractor like this should ignore metrics it don't have permission for, but keep trying the other metrics. Having just CPU and memory usage is still much better than nothing;-)

**Comment by ncabatoff** [comment]
You're welcome @epa095, and I agree.  Let me know if you find any problems with the fix.  New release forthcoming within the week if you don't feel like building from source.
