### ISSUE TITLE
cannot differentiate the same command name

### ISSUE THREAD

**Issue by arrow2012** [ncabatoff/process-exporter#126]
![image](https://user-images.githubusercontent.com/46478986/69933318-41bcc280-1509-11ea-80a1-a92cf8c923d4.png)

there are too many python process on my server ,but the exporter can only see groupname=python on mode=user and mode=system, cannot different which python process
![image](https://user-images.githubusercontent.com/46478986/69933394-85173100-1509-11ea-821b-9f0b9ca7a81d.png)

**Comment by jumbovin** [comment]
adding something like this to your process-selection.yml proved helpful for me
on the downside it will start to track every variant of the arguments 

  - name: "{{.Comm}}:{{.Matches.procDetails}}"
    exe:
      - python
    cmdline:
      - (?P<procDetails>.+)

**Comment by ncabatoff** [comment]
Hi @arrow2012,

Sorry, I don't have enough time to help people with questions here, I only take bug reports and feature requests.
