### ISSUE TITLE
RPM installation for CentOS 6 x64

### ISSUE THREAD

**Issue by kvishnivetsky** [ncabatoff/process-exporter#129]
Hello.

Is it possible to run this software on CentOS 6 x64 and is it possible to install it from RPM package?

**Comment by ncabatoff** [comment]
It should run fine on Centos 6 x64, but I suspect trying to install the RPM package will fail because we assume systemd is available.  You'll probably want to install the .tar.gz file and write an init script  to launch it.

**Comment by kvishnivetsky** [comment]
Running a binary from tar.gz is enougth. Thank you for your reply!
