### ISSUE TITLE
Can not expose the process name of oracle-pmon

### ISSUE THREAD

**Issue by xuanyuanaosheng** [ncabatoff/process-exporter#131]
-----------------------------------------------------------
The first question is `Can not expose the process name of oracle-pmon`:

The oracle process is as below, using ps -ef | grep ora_pmon :

oracle     969     1  0 Sep23 ?        00:17:18 ora_pmon_TESTMON

The oracle home is /u01/app/oracle/product/12.2.0/db_1.

I use the config

process_names:
  - name: "{{.Comm}}"
    cmdline:
    - '.+'

But it failed to expose the oracle process.

---------------------------------------------------------
The second question is how to expose the process, I don't think using expr is a good way :

jira1    23725     1  2 Dec09 ?        08:50:51 /opt/atlassian/jira/jre//bin/java -Djava.util.logging.config.file=/opt/atlassian/jira/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms25600m -Xmx25600m -XX:InitialCodeCacheSize=32m -XX:ReservedCodeCacheSize=512m -Djava.awt.headless=true -Datlassian.standalone=JIRA -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dmail.mime.decodeparameters=true -Dorg.dom4j.factory=com.atlassian.core.xml.InterningDocumentFactory -XX:-OmitStackTraceInFastThrow -Djava.locale.providers=COMPAT -Datlassian.plugins.startup.options= -XX:+UseG1GC -XX:MaxGCPauseMillis=5000 -XX:+ExplicitGCInvokesConcurrent -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Xloggc:/opt/atlassian/jira/logs/atlassian-jira-gc-%t.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=20M -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCCause -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=10.33.191.46 -Dcom.sun.management.jmxremote.port=12345 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dignore.endorsed.dirs= -classpath /opt/atlassian/jira/bin/bootstrap.jar:/opt/atlassian/jira/bin/tomcat-juli.jar -Dcatalina.base=/opt/atlassian/jira -Dcatalina.home=/opt/atlassian/jira -Djava.io.tmpdir=/opt/atlassian/jira/temp org.apache.catalina.startup.Bootstrap start

-----------------------------------------------------------
The last question is how to use the {{.Username}} ? Could you please give some examples?

**Comment by ncabatoff** [comment]
Hi @xuanyuanaosheng,

Sorry, I don't have enough time to help people with questions here, I only take bug reports and feature requests.
