### ISSUE TITLE
Not able to read metrics for process exporter in centos 6 

### ISSUE THREAD

**Issue by pranaya1841** [ncabatoff/process-exporter#135]
Hi Team,

I have  installed process exporter in centos 6 using tar file of version 6(process-exporter-0.6.0.linux-amd64.tar.gz) . service is running successfully but could not able to read the metrics. and we could see there are no data points in grafana dashboard . could you please help me with this issue.

error:
FAILEDESC[0;39m]^M2020/02/02 23:10:05 Reading metrics from /proc based on "/etc/process-exporter/all.yaml. Please help me on this 

This is my all.yaml file

process_names:
  - name: "{{.Comm}}"
    comm:
    - java

**Comment by ncabatoff** [comment]
Hi @pranaya1841,

Sorry, I don't have enough time to answer questions for this repo, I just take bug reports and feature requests.  My generic advice when people are having trouble getting the output they want from process-exporter is: try running it interactively, with `-once-to-stdout-delay=1s` and possibly with `-debug`.
