### ISSUE TITLE
Expose proportional resident memory size 

### ISSUE THREAD

**Issue by PierreF** [ncabatoff/process-exporter#140]
Currently the resident size is the sum of resident size from all process in the group, which will means a rather high value for processed that share significant amount of memory.

Linux do expose a proportional resident memory size in the smaps file, which is 
> The "proportional set size" (PSS) of a process is the count of pages it has
> in memory, where each page is divided by the number of processes sharing it.

I think the sum of PSS is more interesting than sum of RSS, as RSS sum is way too high.

I'm willing to come with a PR, but that need update on procfs dependency and before working on this, I want to known your thought on whether this change should be done on your procfs fork or being submitted to prometheus/procfs and stop using the forked-procfs ? It seems that prometheus/procfs now has ProcStatus support which was the reason of the fork.

**Comment by flixr** [comment]
I'm also seeing this issue, but didn't quite spend enough time to find out where this is coming from...
But "correct" reporting of this would be very very welcome!

**Comment by PierreF** [comment]
I'll start working on PRs to provide this by using prometheus/procfs, that is:
* submit PR here to use prometheus/procfs instead of ncabatoff/procfs
* submit PR on prometheus/procfs to export smaps information
* submit PR here to using smaps information from prometheus/procfs. This PR will depend on the two above.

**Comment by PierreF** [comment]
PRs created:

* wchan gathering was missing on prometheus/procfs => PR https://github.com/prometheus/procfs/pull/280
* Using prometheus/procfs (which require above PR): #141 
* Added gathering of smaps in prometheus/procfs => https://github.com/prometheus/procfs/pull/281
* Final PR (which require all above PRs): #142
