### ISSUE TITLE
Process exporter metrics missing R character in label

### ISSUE THREAD

**Issue by nemke43** [ncabatoff/process-exporter#144]
Hello, did somebody had this issue?
namedprocess_namegroup_cpu_seconds_total{groupname="process-exporte",mode="system"} 0.020000000000000004

I have tried a lot of scenarios while trying to fix.

my config is:
process_names:
  - name: "{{.Comm}}"
    cmdline:
    - '.+'

My process name is always missing letter R at the end . I have tried several versions of process exporter.

**Comment by flixr** [comment]
Comm is always truncated, see /proc/[pid]/comm http://man7.org/linux/man-pages/man5/proc.5.html

**Comment by nemke43** [comment]
Yes, on that location is stored as 

> process-exporte

But, how can I fix that, and where did it pull from?

**Comment by flixr** [comment]
You can't "fix" that as long as you use Comm. Linux just keeps the truncated version.
Either you live with the truncated names, use a different replacement for name than Comm or specify names explicitly.

**Comment by ncabatoff** [comment]
Thanks @flixr!
