### ISSUE TITLE
CPU/Memory usage

### ISSUE THREAD

**Issue by nt-rbmk** [ncabatoff/process-exporter#146]
Hello,

I` ve installed process-exporter to many debian, centos and amazon-linux instances.
On some of them, the process-exporter seems to leak and consumes high CPU usage.
This weird behavior of process-exporter happens to instances that running centos and are being used as dbs.

```
sh-4.2# process-exporter --version
process-exporter version 0.6.0
sh-4.2# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
sh-4.2# cat /etc/default/prometheus-process-exporter 
process_names:
  - comm:
    - node_exporter
    - postmaster
    - process-exporte
    - sshd
sh-4.2# 
sh-4.2# cat /etc/systemd/system/prometheus-process-exporter.service 
[Unit]
Description=prometheus-process-exporter

[Service]
Type=simple
User=prometheus
Group=prometheus
ExecStart=/usr/bin/process-exporter -config.path /etc/default/prometheus-process-exporter
Nice=19

[Install]
WantedBy=multi-user.target

```

Please find attached an example of memory usage (process was restarted, that` s why memory consumption dropped):

![pic1](https://user-images.githubusercontent.com/61050727/81402165-8e9c6900-9139-11ea-812d-7f4601bb965c.png)

Thank you a lot!

**Comment by nt-rbmk** [comment]
An update:
i removed postmaster from the process-exporter config and everything seems to run fine.

**Comment by ncabatoff** [comment]
Hi @nt-rbmk,

Interesting.  I think there is the possibility of leaking a bit of memory over time on busy systems, though the growth you're seeing there in a single day is much higher than I would expect.
