### ISSUE TITLE
process-exporter resident memory and virtual memory as percent query for grafana

### ISSUE THREAD

**Issue by pooja-cha** [ncabatoff/process-exporter#149]
I want to convert the metrics for per processes to percent value instead of GIB,MIB so that it makes more sense to viewers who view grafana dashboard . Need to know the query for it ip specific. Please help. I should be valid for each process separably and for each ip .

**Comment by ncabatoff** [comment]
Hi @pooja-cha,

Sorry, I don't have enough time to answer questions here, I only take bug reports and feature requests.
