### ISSUE TITLE
flag provided but not defined: -config.file

### ISSUE THREAD

**Issue by bljusruk** [ncabatoff/process-exporter#150]
Hi,

I have successfully built process-exporter using the following Dockerfile:

ARG ALPINE=golang:1.14-alpine

FROM $ALPINE as build_image
RUN apk --no-cache upgrade && apk --no-cache add \
    gcc make \
    git curl \
    libc-dev

RUN mkdir -p /app/process-exporter
WORKDIR /app/process-exporter
ENV PATH $PATH:/go/bin

RUN git clone -b v0.6.0 https://github.com/ncabatoff/process-exporter.git /app/process-exporter

RUN make

RUN apk del curl make gcc libc-dev

FROM $ALPINE

RUN chmod +x /bin
COPY --from=build_image /app/process-exporter/process-exporter /bin

COPY config/process-config.yml       /etc/process-exporter/config.yml

EXPOSE      9115
ENTRYPOINT  [ "/bin/process-exporter" ]
CMD         [ "-config.path=/etc/process-exporter/config.yml" ]

I have noticed that the docker container with process-exporter keeps restarting.

docker logs container_id gave me the usage of process-exporter, this being its most relevant part:

flag provided but not defined: -config.file

From the Dockerfile it is clear that process-exporter is given the option -config.path

I was not able to find the reason why process-exporter thinks it got -config.file option.

In case you need any more information please let me know.

Thanks.

**Comment by bljusruk** [comment]
When I used the golang 1.12 (as required in README.md) I was able to start process-exporter without any problems.

**Comment by extrajulius** [comment]
Hi, try changing your CMD to:
CMD ["-config.path", "/etc/process-exporter/config.yml"]
