### ISSUE TITLE
Can process-exporter check the network connection information of the process?

### ISSUE THREAD

**Issue by gordan-code** [ncabatoff/process-exporter#155]
Can process-exporter check the network connection information of the process? Just like lsof -i.
This way, when network traffic soars, I can see which process caused it.

**Comment by ncabatoff** [comment]
Hi @gordan-code,

I have no plans to add this feature.  I agree it would be of value, but I think it would be a lot of work to do it properly, and I don't want it badly enough.  If, as I expect, a proper implementation would mean adding a lot of code to process-exporter, I might not even accept a PR for it, as I feel process-exporter has already grown quite big and complex.  That said, I'm not dead-set against it, just hesitant.
