### ISSUE TITLE
metrics doesn't show all processes

### ISSUE THREAD

**Issue by mikys-next-insurance** [ncabatoff/process-exporter#158]
Hello,
I'm using

```
  - name: "{{.ExeFull}}"
    cmdline:
    - '.+'
```

in the yaml file, but still there are many processes which doesn't show-up in the metrics.
One for example:

```
ps aux | grep zoo
tableau   72048  0.2  0.1 6829120 376792 ?      Ssl  Jul13 125:23 /var/opt/tableau/tableau_server/data/tabsvc/services/appzookeeper_1.20202.20.0626.1424/appzookeeper/appzookeeper run
```

The process exporter is running as root.

Thanks

**Comment by ChSanjayBabu** [comment]
@ncabatoff i am also facing same issue, some processes     are missing in metrics, pls help

**Comment by mikys-next-insurance** [comment]
@ChSanjayBabu The problem was that I installed x84 version of the process-exporter on a 64-bit machine. Once I installed the right version (64-bit) it worked ok. Please check.
