### ISSUE TITLE
restart service process but process-exporter can not find

### ISSUE THREAD

**Issue by zhiyuan192shine** [ncabatoff/process-exporter#160]
I restart HUE service(CDH)，the start way with python command，but process-exporter can not find process.
namedprocess_namegroup_num_procs == 0

**Comment by zhiyuan192shine** [comment]
such as
process_names:
  - name: "{{.Matches}}"
    cmdline:
    - 'runcherrypyserver'

**Comment by ncabatoff** [comment]
Hi @zhiyuan192shine,

Sorry, I don't have enough time to answer questions here, I only take bug reports and feature requests.
