### ISSUE TITLE
Report on thread states

### ISSUE THREAD

**Issue by ncabatoff** [ncabatoff/process-exporter#17]
Split off from #16.  New metrics desired:

Process threads:
- Number of threads in state 'running' (R)
- Number of threads in state 'interruptible sleeping' (S)
- Number of threads in state 'uninterruptible sleeping' (D)

**Comment by flixr** [comment]
This would include #5

**Comment by ncabatoff** [comment]
Filed #22 for the context switches.  I discovered that process state is available in /proc/pid/stat, whereas the context switches it seems do require reading /proc/pid/status.
