### ISSUE TITLE
for Kubernetes: daemonset or sidecar?

### ISSUE THREAD

**Issue by ghostsquad** [ncabatoff/process-exporter#174]
Is this designed to be used as a daemonset or a sidecar?

If daemonset, is there a way to correlate procs to pods that those procs belong to?

**Comment by ncabatoff** [comment]
Hi @ghostsquad,

It wasn't really designed for k8s.  #94 wants to add more k8s-specific stuff, but so far I've been unwilling to pursue that particular enhancement, though I won't rule out better k8s integration/documentation in future.  For now I'm going to close this issue as I don't know the answer to your question and I haven't been using k8s much these last few years.
