### ISSUE TITLE
Support for negative match syntax

### ISSUE THREAD

**Issue by shadowman13** [ncabatoff/process-exporter#176]
Hello,

How can I use the negative match syntax in process exporter? I tried the syntax below but it said didn't support
The syntax was tested ok on regex101

Ex:
  - name: "{{.Comm}}"
    cmdline:
    - ^((?!java).)*$

+Error log:
error reading config file "/etc/process_exporter/config.yml": unable to parse process_name entry 12: bad cmdline regex "{{^((?!java).)*$}}": error parsing regexp: invalid or unsupported Perl syntax: `(?!`

**Comment by ncabatoff** [comment]
Hi @shadowman13,

Sorry, Go regexps are documented [here](https://github.com/google/re2/wiki/Syntax) and lookahead/lookbehind assertions aren't supported.
