### ISSUE TITLE
Can't startup, Reading metrics from /proc for procnames futex stuck

### ISSUE THREAD

**Issue by sunzhaoyang** [ncabatoff/process-exporter#185]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/2182116/108579143-8e83f780-7360-11eb-9947-cf3ee3b7a979.png">

wait startup long time, maybe too many process?

<img width="770" alt="image" src="https://user-images.githubusercontent.com/2182116/108579170-ae1b2000-7360-11eb-876d-8bab1124f116.png">

strace,looks like stuck here forever

<img width="398" alt="image" src="https://user-images.githubusercontent.com/2182116/108579204-d3a82980-7360-11eb-9fc1-fb4c2ef55806.png">

**Comment by ncabatoff** [comment]
Hi @sunzhaoyang,

This is the normal behaviour for process-exporter as you invoked it.
