### ISSUE TITLE
Nerver started process how to monitor

### ISSUE THREAD

**Issue by Lemon-le** [ncabatoff/process-exporter#187]
hi , I have two instance , every instance have process_exporter .

I have a application , cant't run this two instance.

How I use process_exporter monitor , once application process started , alert .

now this two instance nerver run application process , so not key and value.

**Comment by ncabatoff** [comment]
Hi @Lemon-le,

Sorry, I don't provide help for running process-exporter.  I'll try to investigate bug reports now and then when I have time, but that's the extent of it at this point.
