### ISSUE TITLE
[REQUEST] Building an armv7 and arm64 in docker hub

### ISSUE THREAD

**Issue by Elrondo46** [ncabatoff/process-exporter#194]
Can you do this ?

It's needed for RPi

**Comment by ncabatoff** [comment]
Hi @Elrondo46,

I'm open to the idea, and will probably do this someday.  However, I don't run docker on my RPis though, and I don't yet know how to build multi-arch docker images, so I'm not sure when it will happen.

**Comment by Elrondo46** [comment]
Check my pull request

**Comment by ncabatoff** [comment]
Hmm, interesting.  I'm not sure I want to have a hybrid build system that uses both CircleCI and Github Actions.  On the other hand I've been contemplating switching to Github Actions anyway, so if I take that route I'll be sure to consider your solution for generating the image outputs.

**Comment by Elrondo46** [comment]
Thanks it is done
