### ISSUE TITLE
How do I build process-exporter for deployment without docker?

### ISSUE THREAD

**Issue by mmshaikh88** [ncabatoff/process-exporter#25]
I would like to build or download process-exporter binaries for Ubuntu and CentOS. Please let me know how can I build for CentOS and Ubuntu without using docker image.

**Comment by mmshaikh88** [comment]
I found the tgz binaries under release section.

**Comment by flixr** [comment]
@mmshaikh88 can you close this if it is solved for you?

**Comment by manikSMahajan** [comment]
Assuming you GOPATH = /usr/local/go
To build process exporter
1. Clone the process exporter using go get github.com/ncabatoff/process-exporter
2. Go to /usr/local/go/bin/src/github.com/ncabatoff/process-exporter/cmd/process-exporter and fire go build command
3. If everything goes all right then you will get binary in the same folder(If you get any  missing packages then simply get it with "go get")
