### ISSUE TITLE
Remove process group when namedprocess_namegroup_num_procs = 0

### ISSUE THREAD

**Issue by zviRosenfeldRedis** [ncabatoff/process-exporter#282]
I'm tracking processes that die after a while, and are never expected to come back. So I don't want these process groups to appear in the stats once the process dies. But in practice I continue seeing it (and `namedprocess_namegroup_num_procs` for it is 0). It only disappears when I restart process-exporter.
Is there a way I can cause the process group to disappear when `namedprocess_namegroup_num_procs` for it is 0?

**Comment by zviRosenfeldRedis** [comment]
Update: I merged a fix for this into a fork: https://github.com/RedisLabs/process-exporter. I added a flag `remove-empty-groups`, and if that flag is true we forget any group with no processes (default is false).

I also opened a PR back upstream to with my fix, but seeing how this repository wasn't updated since 2021, I doubt it's ever getting it...

**Comment by Alex-wwei** [comment]
It seems to have been removed, but as time went on, the exporter's memory footprint increased.

**Comment by zviRosenfeldRedis** [comment]
I pushed a fix into the repository that probably fixed the issue. (into this repository: https://github.com/RedisLabs/process-exporter).
@Alex-wwei, can you confirm if the bug was indeed fixed?

**Comment by Alex-wwei** [comment]
> I pushed a fix into the repository that probably fixed the issue. (into this repository: https://github.com/RedisLabs/process-exporter). @Alex-wwei, can you confirm if the bug was indeed fixed?

@zviRosenfeldRedis It`s much better now, But there may still be a slight increase in memory due to the constant changes in the process。

**Comment by SilenceAdele** [comment]
hi @zviRosenfeldRedis  The parameter of `emove-empty-groups` is very usefully. But the current newest version （v0.8.5）of process-exporter readme document  is not update. Plase update it，make more people to use it. Thank you very much, best wish for you.

**Comment by zviRosenfeldRedis** [comment]
Good point @SilenceAdele. I created a PR to add it: https://github.com/ncabatoff/process-exporter/pull/335
