### ISSUE TITLE
process-exporter omits some processes

### ISSUE THREAD

**Issue by flixr** [ncabatoff/process-exporter#29]
I have the problem that the process-exporter quite often misses some processes although they are specified in the yml file (as `comm`).

The process that is missing is actually running and e.g. doing a `process-exporter -config.path foo.yml -once-to-stdout` shows the process correctly.
Also restarting the process-exporter works.

Also I'm not getting any scrape errors...

Any ideas on what is going on here?

**Comment by flixr** [comment]
There is a TODO in https://github.com/ncabatoff/process-exporter/blob/994feb87ab7d744b26789d23cae5f02039660346/proc/tracker.go#L294

by printing all PIDs that are not (yet?) here, I could confirm that the missing processes (which are actually running) are skipped here...
Also there are quite a few printed and it sounds like this should not be the case?

**Comment by flixr** [comment]
So the problem seems to be that I start some processes with a wrapper script (that first sets some env variables, etc..) and then calls `exec` for starting the actual process.
If the process-exporter sees the process PID for the first time and the `comm` name is still `bash` (because it's still in the loading phase before `exec` is called in the script), it will forever ignore this process...

Any ideas on how to handle this?

**Comment by ncabatoff** [comment]
Fixed by PR #30.  Thanks @flixr.
