### ISSUE TITLE
Process-exporter new release need with latest go and exporter toolkit

### ISSUE THREAD

**Issue by krdineshbny** [ncabatoff/process-exporter#292]
Process-exporter new release need with latest go and exporter toolkit
the last release is on 2021 Can we get a new release with latest dependencies and exporter tool kit?

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/process-exporter

**Comment by ncabatoff** [comment]
Sorry for the delay, https://github.com/ncabatoff/process-exporter/releases/tag/v0.7.11 should address both.

**Comment by krdineshbny** [comment]
Thanks @ncabatoff

**Comment by krdineshbny** [comment]
@ncabatoff  linux amd64 binary is missing the libraries.
Can you please check this?
[dinesh@XYZ123 process-exporter-0.7.11.linux-amd64]$ ./process-exporter
./process-exporter: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./process-exporter)
./process-exporter: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./process-exporter)

**Comment by ncabatoff** [comment]
That's strange, I'm using CGO_ENABLED=0, so I wouldn't expect to be depending on any shared libraries.  I'll look into it later today, after work.

**Comment by krdineshbny** [comment]
[xbbls8w@XYZ123 process-exporter-0.7.11.linux-386]$ ./process-exporter --version
process-exporter, version 0.7.11 (branch: , revision: 6caf441369fedd7a526d0ace7aed9156afbf9073)
  build user:       goreleaser
  build date:       2024-04-16T23:41:57Z
  go version:       go1.22.2
  platform:         linux/386
  tags:             netgo

The 386 binary works and i see the problem only on the amd64 binary

[xbbls8w@XYZ123 process-exporter-0.7.11.linux-amd64]$ ./process-exporter --version
./process-exporter: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./process-exporter)
./process-exporter: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./process-exporter)

**Comment by ncabatoff** [comment]
Ok, so my goreleaser config wasn't setting CGO_ENABLED=0, unlike the makefile and dockerfile.  It worked previously because using the build tag netgo was sufficient, now I'd also need osusergo, or alternatively just set the env var, which is what I settled on.  I've tested the amd64 binary from the 0.8.1 release and ldd says it's not a valid dynamic program, which is what we want.
