### ISSUE TITLE
Process Exporter v0.7.11 is missing library GLIBC_2.34

### ISSUE THREAD

**Issue by krdineshbny** [ncabatoff/process-exporter#293]
@ncabatoff linux amd64 binary is missing the libraries.
Can you please check this?

[dinesh@XYZ123 process-exporter-0.7.11.linux-amd64]$ ./process-exporter
./process-exporter: /lib64/libc.so.6: version GLIBC_2.34' not found (required by ./process-exporter) ./process-exporter: /lib64/libc.so.6: version GLIBC_2.32' not found (required by ./process-exporter)

**Comment by ncabatoff** [comment]
Fixed in release 0.8.1
