### ISSUE TITLE
package naming convention 

### ISSUE THREAD

**Issue by Dupontem** [ncabatoff/process-exporter#39]
Hello, 
Thank-you very much for that exporter.
I have two remarks to improve the binaries packaging. 

The underscore separator  in the  2.5.0 package name create a singularity  with other exporters (and applications):
```
elasticsearch_exporter-1.0.2.linux-amd64.ta
hadoop_exporter-1.0.linux-amd64.tar.gz
node_exporter-0.15.2.linux-amd64.tar.gz
process-exporter-0.1.0.linux-amd64.tar.gz
process-exporter_0.2.5_linux_amd64.tar.gz       <----<<< _0.2.5_linux_
```

I don't mind a lot as it is just a convention but it had side effect on Ansible deployment role as in the role the package name is made from the version given as parameter so perhaps I will not be the only one to face this issue. 

Another formal change is the package content. 
The files were stored into a directory of the same name as the archive, now files are going to the current directory:  

```
$ tar tzf process-exporter-0.1.0.linux-amd64.tar.gz
process-exporter-0.1.0.linux-amd64/
process-exporter-0.1.0.linux-amd64/LICENSE
process-exporter-0.1.0.linux-amd64/process-exporter

$ tar tzf process-exporter_0.2.5_linux_amd64.tar.gz
LICENSE
README.md
cmd/process-exporter
```
Here also it makes deployment scripts a bit more complicated to match any version

**Comment by mar1ged** [comment]
Can you add a `--strip-components=1` to the tar command in order to remove the path containing the version information ?

**Comment by Dupontem** [comment]
no thank you I will not change anything, I was making a suggestion you should follows the standards.

**Comment by ncabatoff** [comment]
I don't think there are any real standards with respect to these questions.  I do prefer to have tarballs contain a subdirectory however, and since I was making that change anyway I figured I might as well change the name format to be more consistent with those other exporters.
