### ISSUE TITLE
Process Exporter Default Binding in DEB package

### ISSUE THREAD

**Issue by PeterZaitsev** [ncabatoff/process-exporter#40]
Now we have Debian package and startup script which is great!

The problem however it changes  default from the previous default to bind to local host only:

root@mysql8:~# ps aux | grep process
root     15556  0.0  0.9  13260  9292 ?        Ssl  15:31   0:00 /usr/bin/process-exporter --config.path /etc/process-exporter/all.yaml --web.listen-address=127.0.0.1:9256

This makes it not overly useful by default as it is unlikely you have Prometheus Server running on the same host.

**Comment by ncabatoff** [comment]
Whoops, thanks for pointing that out!
