### ISSUE TITLE
Mapping process according to users of the same process

### ISSUE THREAD

**Issue by samuelthan** [ncabatoff/process-exporter#42]
My top example is as follows, 

 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND          
13168 ahfvw0d1  30  10  498m  35m  20m S  0.0  0.2   0:03.49 php-cgi      
 8859 realnoni  30  10  495m  33m  20m S  0.0  0.2   0:11.27 php-cgi      
 6590 asjzdiwq  30  10  495m  32m  20m S  0.0  0.2   0:13.34 php-cgi      
 5657 holeyrai  30  10  495m  31m  19m S  0.0  0.2   0:04.47 php-cgi      
14480 ripplecr  30  10  498m  31m  17m S  0.0  0.2   0:02.90 php-cgi      
14442 ripplecr  30  10  497m  31m  17m S  0.0  0.2   0:02.00 php-cgi      
10720 computer  30  10  496m  31m  18m S  0.0  0.2   0:08.75 php-cgi      
16126 realnoni  30  10  484m  30m  18m S  0.0  0.2   0:12.08 php-cgi      
31561 a0w4pkbp  30  10  496m  30m  17m S  0.0  0.2   0:03.54 php-cgi      
31565 ahfvw0d1  30  10  484m  29m  17m S  0.0  0.2   0:05.80 php-cgi      
21275 asjzdiwq  30  10  484m  29m  18m S  0.0  0.2   0:01.77 php-cgi      

I'm using the YAML file approach to configure which kind of process to monitor. As such
process_names:
  - comm:
     - httpd
     - php-cgi
     - memcached
     - node_exporter

  - exe:
    - /usr/bin/php-cgi

   - name: "{{.ExeFull}}:{{.Matches.Cfgfile}}"
    exe:
    - /usr/local/bin/process_exporter
    cmdline:
    - -config.path\\s+(?P<Cfgfile>\\S+)

What i'm getting in return is a summed value of php-cgi instead of each individual users
![summedphpcgi](https://user-images.githubusercontent.com/232591/40468360-8f502b0e-5f70-11e8-813c-cb1fc8c7a783.PNG)

How do i go about separating the php-cgi to have breakdowns by users ?

**Comment by ncabatoff** [comment]
Not possible presently: this is a feature request.  I would implement this by adding a .Username template macro so you can group by it.

**Comment by samuelthan** [comment]
Cool, looking forward to it. Great exporter btw !!

**Comment by xuanyuanaosheng** [comment]
@ncabatoff COuld you please giva some example about "Username template"?
