### ISSUE TITLE
Regex to track all process

### ISSUE THREAD

**Issue by vivekbny** [ncabatoff/process-exporter#43]
Is it possible to use regex to track all process running in a machine or choose the top processes ?
@ncabatoff @flixr

**Comment by flixr** [comment]
By default child processes are tracked as well, so you could just select the top processes you want...

You could also specify a catch-all regex, although this will waste some performance for the regex check:
```
process_names:
  - cmdline: 
    - .+
```

**Comment by vivekbny** [comment]
@flixr Thanks this worked, also is there a way to select processes for a specific user
