### ISSUE TITLE
Allow to get user name label for processess

### ISSUE THREAD

**Issue by PeterZaitsev** [ncabatoff/process-exporter#47]
I recognize it is tricky with flexible group definition but I think it would be great to expose the  user which owns the process as a label which would allow to aggregate the same data by user which is helpful for some workloads.

namedprocess_namegroup_cpu_system_seconds_total{groupname="acpid"} 0
namedprocess_namegroup_cpu_system_seconds_total{groupname="agetty"} 0
namedprocess_namegroup_cpu_system_seconds_total{groupname="apt-check"} 0

It would be great to get   user="root"   label added

**Comment by ncabatoff** [comment]
This is a dup of #42.
