### ISSUE TITLE
[feature request] add number of threads

### ISSUE THREAD

**Issue by flixr** [ncabatoff/process-exporter#5]
Hi,

this is already immensely useful, but would be even better if it would include the number of threads (which is also available from proc).

Cheers, Felix

**Comment by ncabatoff** [comment]
Sorry @flixr, I let this one slip by me.  I'll try to get to it next week.

**Comment by flixr** [comment]
The simple numThreads (without status as per #17) is already available in prometheus/procfs

**Comment by ncabatoff** [comment]
Thanks for the PR.   I'm going to hold off on merging it until we decide what to do about #19 and #17, since it may make this redundant.

**Comment by flixr** [comment]
I first thought so as well, but I now think this would make sense in any case as it doesn't cost more and #19 would probably be configurable for only some processes. (And #17 is basically a subset of #19)

**Comment by ncabatoff** [comment]
#17 need not be a subset of #19, as described it was going to give a count of how many threads are in which state.  I agree that given #19 it may make more sense to report these counts on the more granular per-threadname basis it will introduce, but I haven't fully made up my mind.  I think I might want the #17 metrics for my primary use case, where I may not be able to tolerate the huge increase in metric count that the #19 threaded-mode will bring in.  Then again, with the huge resource savings Prometheus 2 will bring, maybe I shouldn't be worrying so much about the number of metrics.

**Comment by ncabatoff** [comment]
I thought about it some more and I decided that as you say it's a useful metric and adding this doesn't require any extra files so it's cheap.  And some people who don't want the extra overhead of parsing the per-thread files may want this metric.
