### ISSUE TITLE
V 0.3.9 Error reading metrics for pid

### ISSUE THREAD

**Issue by aagrytskov** [ncabatoff/process-exporter#57]
Hi. Download the docker image and download the rpm file for linux amd64 and had seen the error. Running with any configuration file or standard configuration:
`16:48:57 error reading metrics for {Pid:31819 StartTimeRel:1435632}: line 25 from status file without ':':
 16:48:57 error reading metrics for {Pid:31820 StartTimeRel:1435632}: line 25 from status file without ':':
 16:48:57 error reading metrics for {Pid:31821 StartTimeRel:1435632}: line 25 from status file without ':':`
In version 0.3.7 all works.

**Comment by ncabatoff** [comment]
Interesting, it sounds like your kernel produces some /proc/[pid]/status lines that are empty.  It should be easy enough to tolerate it, I'll have a fix out shortly.
