### ISSUE TITLE
Inconsistent Handling of the Process Threads

### ISSUE THREAD

**Issue by PeterZaitsev** [ncabatoff/process-exporter#58]
It looks like different data is handled inconsistently for threads belonging to the process

for namedprocess_namegroup_cpu_user_seconds_total   the value seems to include all the threads,  same for  namedprocess_namegroup_read_bytes_total  however  namedprocess_namegroup_context_switches_total seems to only report value from the main thread which is not meaningful value for threaded processes.

**Comment by ncabatoff** [comment]
I fixed this in the pre-release v0.3.11, by reading the thread data whether or not -threads is given.  The thread-based metrics are only emitted when -threads is given, as before.  I haven't yet decided whether to eliminate the option altogether and always emit them.
