### ISSUE TITLE
states vs num_procs discrepancy

### ISSUE THREAD

**Issue by szymonpk** [ncabatoff/process-exporter#64]
I have only one named group, running process-exporter 0.4.0 and I have noticed strange discrepancy between num_procs (`namedprocess_namegroup_num_procs`) metrics and sum of states (`namedprocess_namegroup_states{state="Sleeping"}`).

num_procs shows 22 processes, which is fine and it is number of procsseses (`ps aux ... | wc -l`). All processes in the group are sleeping and sum of sleeping processes shows exactly twice as much - 44. 

And I am not sure why. Is this some kind of a bug? /proc is read twice? Or I misunderstood this metric?

I have also noticed, if num_procs is 1 it is not multiplicated in states metric, otherwise it is always doubled.

**Comment by szymonpk** [comment]
OK I have found this [this commit](https://github.com/ncabatoff/process-exporter/commit/5f72f865f7449d11c1b9277172b2f4428743604f), now it makes sense, since I have 43 threads for this case. 

It is kind confusing, since documentation states it is based on **processess**, not threads.

**Comment by ncabatoff** [comment]
Thanks for the fix!  Sorry that my failure to update the docs cost you some time.  I'll review it now and make sure there's nothing else I missed.

**Comment by szymonpk** [comment]
No worries ;-) thanks for building and maintaining process-exporter!
