### ISSUE TITLE
Does Process exporter supports AIX and Solaris OS

### ISSUE THREAD

**Issue by krdineshbny** [ncabatoff/process-exporter#70]
Hi we are using process exporter for linux machines and it is working fine.
But when we tried using it for AIX the binaries are not working.
Does Process exporter supports AIX and Solaris OS.
If it is not supported is there any workarounds available for these Operating Systems.

Regards
Dinesh KR

**Comment by ncabatoff** [comment]
Hi Dinesh,

process-exporter only works on Linux.  It's not hard to build a Go binary that will run on Solaris (I think), but we rely on the contents of /proc to gather the metrics, and /proc is very OS-specific.  I haven't used either OS in almost twenty years so I don't have any suggestions for workarounds or alternatives I'm afraid.
