### ISSUE TITLE
tar.gz package improvements

### ISSUE THREAD

**Issue by viktorradnai** [ncabatoff/process-exporter#72]
Hi, could you please include the `all.yml` file in the tar.gz for the next release? At least blackbox exporter ships with a basic config which I find useful (I'm maintaining a Chef cookbook that deploys a bunch of exporters). 

Also on the topic of packaging, the other exporters all seem to have an underscore between 'thing' and 'exporter' eg `process_exporter` rather than `process-exporter`. This applies to the tar.gz archive, the directory contained within that and the name of the executable as well.

**Comment by ncabatoff** [comment]
Hi @viktorradnai,

Re the tar.gz: sure thing, I can add all.yml. 

Re underscores vs dashes: I don't feel the need to be consistent with other exporters in this regard.  I'd rather not break any existing scripting others may have built up around process-exporter already.

**Comment by viktorradnai** [comment]
Thanks for bundling `all.yml`. I understand your reasoning for not wanting to rename the executable and I will work around this then.
