### ISSUE TITLE
unable to collect metrics for some processes on 32bit arm

### ISSUE THREAD

**Issue by flixr** [ncabatoff/process-exporter#80]
At some point during runtime I suddenly didn't get any metrics for some processes anymore.

After adding some more debug output (see #79) I got this:
```
2019/01/15 13:10:05 error getting proc ID for pid 2434: integer overflow on token 2264576000
```

It seems this is because `ProcStat` in `procfs/proc_stat.go` uses too small integers for some fields.
in my case it is the `vsize` field that has the overflow.
The `vsize` should be unsigned as well.

Note that this happend on armv6, so 32bit.

**Comment by ncabatoff** [comment]
I've merged in the upstream changes, thanks!  I've only done smoke testing on amd64 so far, but I expect you'll be pleased to hear that I'm now using pi zeros in my home cluster, and they're running process-exporter!  So you should no longer be the sole finder of armv6/32-bit issues.
