### ISSUE TITLE
How to interpret results

### ISSUE THREAD

**Issue by vkuznet** [ncabatoff/process-exporter#87]
I'm trying to verify results I'm getting from process-exporter and so far they don't match with what I'm getting from a filesystem. Here is my config:
```
process_names:
 - exe:
   - prometheus
   cmdline:
   - ".*consoles.*"
```
which I used to match prometheus process on my Linux system.

The report I got from `curl http://localhost:9256/metrics` call to process-exporter I see
```
process_resident_memory_bytes 9.981952e+06
process_virtual_memory_bytes 1.14376704e+08
```

Now the results I get from top or ps tools show totally different numbers:
```
ps auxww | grep 20030
prometh+ 20030  0.1  4.4 149516 82800 ?        Ssl  Feb21   2:40 /usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries
```
Here `ps` commands reports RES size 82800 KiB and VSZ size 149516 KiB. So, my question is how should I interpret process_resident_memory_bytes and process_virtual_memory_bytes, and why these numbers do not match RES/VSZ numbers, I see they are off by order of magnitude.

**Comment by vkuznet** [comment]
Also, if I look-up number of file descriptors, the `/proc/<pid>/fd | wc -l` tells me 18 while process-exporter reports 7. I'm not really sure what exactly process-exporter reports.

**Comment by vkuznet** [comment]
Further investigation reveals that the reported numbers are for exporter service and not for underlying monitoring one. Why I can't get numbers for requested monitoring process (in this case I was trying to monitor prometheus server itself) is still unclear to me. May be again it is question of configuration, see #85.

**Comment by baryluk** [comment]
You are looking at the wrong metric, check `namedprocess_namegroup_open_filedesc` and `namedprocess_namegroup_memory_bytes`  (these are the literal names of the metrics).

The one you were looking before, are indeed for the exporter itself, they are exported by Go automatically, and are used to monitor the exporter itself. Not the processes that exporter monitors and exports.

**Comment by ncabatoff** [comment]
Thanks @baryluk , you are exactly correct.  @vkuznet , I'm going to close this issue because I think it's been addressed, please re-open if you disagree.
