### ISSUE TITLE
Fails to find/track the single process I'm interested in 

### ISSUE THREAD

**Issue by KristoferHansson** [ncabatoff/process-exporter#89]
I'm using process_exporter for Prometheus but it does for some reason fail to find the single process I'm looking for.

The process shows up fine in "top". Listing /proc shows 124 running processes and there seems to be nothing special about the process in question. the /proc/pid/stat shows the "comm" name as value 2 (QtDisp) as expected.

Running process_exporter with -debug and grep:ing for "found new proc" clearly shows that it only finds 123 out of the 124 processes running, the one missing is the one I'm looking for!

The process in question is last in a chain of X parent processes but process exporter is able to find another process at the same level in the chain.

If I restart(not with the same startup script chain as during boot) the process I'm interested in monitoring from command line, and then restart process_exporter, then it finds it. This is unfortunately not a valid workaround for me.

During startup, starting process_exporter before the process of interest seems to catch it for a brief time, then "loosing track" of it (no more metrics sent after first few scrapes, running top still shows the process active).

Any ideas?

**Comment by ncabatoff** [comment]
Hi @KristoferHansson,

That is indeed puzzling.  Let me see if I've got this straight:
- post-boot restart of QtDisp, then restart exporter => QtDisp found
- post-boot restart exporter => QtDisp not found
- post-boot restart of QtDisp => QtDisp not found

You weren't explicit about the last two, I'm kind of reading between the lines, but if you haven't tried those, could you please?

You've grepped the debug log for "found new proc", have you grepped for errors?

One possible flaw of the exporter you may be falling victim to is that when a process changes names we don't detect it.  This is an optimization I'm planning on revisiting soon.  So if QtDisp starts with the some other name, or maybe is launched by a shell script that then calls exec, its metrics may be lumped into the wrong group.

**Comment by KristoferHansson** [comment]
Hi Ncabatoff

We did actually find the issue this last Friday and will be trying to
create a patch and set up a pull request the coming week, it was an issue
in a referenced lib used for the proc parsing.

/Kristofer

**Comment by ncabatoff** [comment]
Hi @KristoferHansson ,

Be aware that I just updated the procfs dependency, so if it was something already fixed upstream there, process-exporter master should contain the fix as of d0323f999df086d87daec4ad36bfa9cdc22338de.

**Comment by BilouteMaif** [comment]
Hi all,

We have almost the same problem except that our process is never detected.
On a redhat 6.9, the 0.5.0 version solve the problem. The java process is finally detected.
But on a redhat 7.4 we have an error in the log.

`error getting proc ID for pid 107364: unsigned integer overflow on token 295677644800`

any idea please ? Is it the same issue than yours ?

Os version:
`Linux 3.10.0-229.20.1.el7.x86_64 #1 SMP Thu Sep 24 12:23:56 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by ncabatoff** [comment]
Hi @BilouteMaif,

Please open a new issue, this is a different bug.  Could you provide one additional piece of information in it please?  On the machine where this is happening, run

```
cat /proc/<pid>/stat
```

replacing <pid> with the pid in the error message, `107364` in the example you gave.
