### ISSUE TITLE
monitoring multiple issues

### ISSUE THREAD

**Issue by vladip1** [ncabatoff/process-exporter#97]
hi

i have 4 different java processes running in the same environment and i would like to see counters of each of them. Could you please help to build the config.yaml file (having really hard time doing it)

Please see the grep command results:

ps -ef | grep java
496       3267     1 99 Apr18 ?        17-19:48:41 /usr/bin/java -Xms8g -Xmx8g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid -d -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch
root     21681     1 87 13:10 ?        04:45:40 /usr/bin/java -Djava.util.logging.config.file=/opt/radware/mgt-server/third-party/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms3072M -Xmx6000M -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/radware/storage/maintenance/ -Dvision.keystore.file=/opt/radware/ssl/vision.keystore -Djavax.net.ssl.keyStore=/opt/radware/ssl/vision.keystore -Djavax.net.ssl.keyStorePassword=radware -Djavax.net.ssl.trustStore=/opt/radware/ssl/vision.keystore -Dcollector.properties.location=/opt/radware/mgt-server/third-party/tomcat/conf/ -server -Dendpoints.jmx.unique-names=true -Dsnmp4j.LogFactory=org.snmp4j.log.Log4jLogFactory -Dreporter.profile=vision-production -Dalertsservice.profile=alert-vision-production -Dconfigsync.profile=production -Dvrm.profile=production -Dspring.profiles.active=production -Dcollector.profile=vision-production -Drt-alert.profile=rt-alert-vision-production -Djava.endorsed.dirs=/opt/radware/mgt-server/third-party/tomcat/endorsed -classpath /opt/radware/mgt-server/third-party/tomcat/bin/bootstrap.jar:/opt/radware/mgt-server/third-party/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/opt/radware/mgt-server/third-party/tomcat -Dcatalina.home=/opt/radware/mgt-server/third-party/tomcat -Djava.io.tmpdir=/opt/radware/mgt-server/third-party/tomcat/temp org.apache.catalina.startup.Bootstrap start
root     27510     1  0 Apr29 pts/0    00:04:29 java -Xmx1024M -Dvdirect.path=/opt/radware/storage/vdirect/database -Djava.net.preferIPv4Stack=true -Dvdirect.quiet=true -cp vdirect-server-start.jar:lib/* com.radware.vdirect.server.Main
root     27820     1  1 Apr29 pts/0    00:32:27 /usr/bin/java -Djava.util.logging.config.file=/opt/radware/storage/mgt-server/third-party/tomcat2/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms1024M -Xmx1024M -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/radware/storage/maintenance/ -Dvision.keystore.file=/opt/radware/ssl/vision.keystore -Djavax.net.ssl.keyStore=/opt/radware/ssl/vision.keystore -Djavax.net.ssl.keyStorePassword=radware -Djavax.net.ssl.trustStore=/opt/radware/ssl/vision.keystore -server -Dendpoints.jmx.unique-names=true -Dsnmp4j.LogFactory=org.snmp4j.log.Log4jLogFactory -Dalertsservice.profile=alert-vision-production -Dreporter.profile=vision-production -Dconfigsync.profile=production -Dspring.profiles.active=production -Drt-alert.profile=vision-production -Djava.endorsed.dirs=/opt/radware/storage/mgt-server/third-party/tomcat2/endorsed -classpath /opt/radware/storage/mgt-server/third-party/tomcat2/bin/bootstrap.jar:/opt/radware/storage/mgt-server/third-party/tomcat2/bin/tomcat-juli.jar -Dcatalina.base=/opt/radware/storage/mgt-server/third-party/tomcat2 -Dcatalina.home=/opt/radware/storage/mgt-server/third-party/tomcat2 -Djava.io.tmpdir=/opt/radware/storage/mgt-server/third-party/tomcat2/temp org.apache.catalina.startup.Bootstrap start
root     28463 28442  3 Apr29 pts/0    01:46:10 /usr/lib/jvm/java-1.8.0/bin/java -Dprogram.name=run.sh -server -Dserver.side=true -Dinsite.home=/opt/radware/mgt-server -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true -Xms2000M -Xmx4000M -XX:+UseCodeCacheFlushing -XX:CodeCacheMinimumFreeSpace=4m -XX:-UseParallelGC -XX:+AggressiveOpts -Djava.protocol.handler.pkgs=javax.net.ssl -Dhttps.port=8443 -Dhttps.second.port=5443 -Dvision.keystore.file=/opt/radware/ssl/vision.keystore -Dvision.keystore.password=radware -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/radware/storage/maintenance/ -Dsun.rmi.dgc.client.gcInterval=600000 -Dsun.rmi.dgc.server.gcInterval=600000 -Djava.rmi.server.uselocalHostname=false -Djava.rmi.server.hostname=172.17.160.107 -Djava.io.tmpdir=/opt/radware/storage/tmp/application -Djava.endorsed.dirs=/opt/radware/mgt-server/third-party/jboss-4.2.3.GA/lib/endorsed -classpath .:/opt/radware/mgt-server/third-party/jboss-4.2.3.GA/bin/run.jar:/usr/lib/jvm/java-1.8.0/lib/tools.jar org.jboss.Main -c insite -b 0.0.0.0 -c insite -DSERVER_IP=ipv
root     29970 20012  0 18:35 pts/4    00:00:00 grep java
root     31415     1  2 Apr29 pts/0    01:09:03 /usr/bin/java -Djava.util.logging.config.file=/opt/radware/novis/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.net.preferIPv4Stack=true -Xms512M -Xmx1300M -Dresolution=96 -Djava.endorsed.dirs=/opt/radware/novis/tomcat/endorsed -classpath /opt/radware/novis/tomcat/bin/bootstrap.jar:/opt/radware/novis/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/opt/radware/novis/tomcat -Dcatalina.home=/opt/radware/novis/tomcat -Djava.io.tmpdir=/opt/radware/novis/tomcat/temp org.apache.catalina.startup.Bootstrap start

**Comment by ncabatoff** [comment]
Hi @vladip1,

It looks like you have 6 java processes, not 4 - which are the ones you want to monitor?  I'll assume you want all 6.

Having had to do something similar years ago, I think you should do something like:

- one cmdline rule for tomcat that matches and captures the catalina.home value (or some part of it) and includes that in the group name, so you'd end up with the three groups tomcat-radware/mgt-server, tomcat-radware/storage, tomcat-radware/novis
- another rule that looks explicitly for org.elasticsearch.bootstrap.Elasticsearch 
- another for jboss that either matches on org.jboss.Main or -Dinsite.home=/opt/radware/mgt-server or both
- another that matches on com.radware.vdirect.server.Main

Let me know if you still need help, it wasn't clear where you were having difficulties.

**Comment by vladip1** [comment]
Hi thanks for the prompt answer.. I am not clear how to place all the rules together in the same config file.. I tried all different approaches but it didn’t work out. Could you please give an example?

**Comment by ncabatoff** [comment]
Sure:

```
process_names:
  - name: "tomcat:{{.Matches.CatalinaHome}}"
    comm: 
      - java
    cmdline: 
      - -Dcatalina.home=/opt/radware/(?P<CatalinaHome>[^/]+)
  - name: elasticsearch
    comm: 
      - java
    cmdline: 
      - org.elasticsearch.bootstrap.Elasticsearch
  - name: jboss
    comm: 
      - java
    cmdline: 
      - org.jboss.Main
  - name: vdirect
    comm: 
      - java
    cmdline: 
      - com.radware.vdirect.server.Main
```

**Comment by vladip1** [comment]
Thanks a lot!!
